services:
    - docker

before_install:
    - docker build -t fabiopitte/docker-multi -f ./client/Dockerfile.dev .

script:
    - docker run -e CI=true fabiopitte/docker-multi npm run test

after_success:
    - docker build -t fabiopitte/multi-client ./client
    - docker build -t fabiopitte/multi-nginx ./nginx
    - docker build -t fabiopitte/multi-server ./server
    - docker build -t fabiopitte/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push fabiopitte/multi-client
    - docker push fabiopitte/multi-nginx
    - docker push fabiopitte/multi-server
    - docker push fabiopitte/multi-worker

language: generic

dist: xenial

os: linux
